name: instagram
description: instagram app of ddd.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_state_notifier: ^0.7.1
  async: ^2.8.2
  freezed_annotation: ^2.1.0
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  firebase_storage: ^10.3.7
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  ntp: ^2.0.0
  intl: ^0.17.0
  uuid: ^3.0.6
  analyzer: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true
