// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATHeK4yg5L3u5UJXylOCWP4GZYO4edcfc',
    appId: '1:545457961278:web:55c8ee5ad902e7ff5e146f',
    messagingSenderId: '545457961278',
    projectId: 'instagram-clone-47452',
    authDomain: 'instagram-clone-47452.firebaseapp.com',
    storageBucket: 'instagram-clone-47452.appspot.com',
    measurementId: 'G-9KCXFNLZ6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtUlpeBI8mDpOausfCbpL_fqL-69KHYaQ',
    appId: '1:545457961278:android:0ac3993eb925aadd5e146f',
    messagingSenderId: '545457961278',
    projectId: 'instagram-clone-47452',
    storageBucket: 'instagram-clone-47452.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDf15x3sbCz5rjtigvXS0uMXnlPdaWsa0',
    appId: '1:545457961278:ios:e7e10cd5e8fdbb405e146f',
    messagingSenderId: '545457961278',
    projectId: 'instagram-clone-47452',
    storageBucket: 'instagram-clone-47452.appspot.com',
    iosClientId: '545457961278-6t1n0h1jsoch473qoqppsr1flll7ab2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDf15x3sbCz5rjtigvXS0uMXnlPdaWsa0',
    appId: '1:545457961278:ios:e7e10cd5e8fdbb405e146f',
    messagingSenderId: '545457961278',
    projectId: 'instagram-clone-47452',
    storageBucket: 'instagram-clone-47452.appspot.com',
    iosClientId: '545457961278-6t1n0h1jsoch473qoqppsr1flll7ab2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
